nav:
    - Home: index.md
    - Getting started:
          - KServe Quickstart: get_started/README.md
          - First InferenceService: get_started/first_isvc.md
    - Administration Guide:
          - Install KServe:
                - Serverless installation: admin/serverless.md
                - Kubernetes deployment installation: admin/kubernetes_deployment.md
                - ModelMesh installation: admin/modelmesh.md
          - KServe Configurations:
              -  InferenceService configuration: admin/config.md
          - KServe Observability:
                - Logging: admin/logging.md
                - Metrics: admin/metrics.md
                - Distributed Tracing: admin/dt.md
    - User Guide:
          - Concepts:
                - Control Plane: modelserving/control_plane.md
                - Data Plane: modelserving/data_plane.md
          - Single Model Serving:
            - Tensorflow: modelserving/v1beta1/tensorflow/README.md
            - PyTorch: modelserving/v1beta1/torchserve/README.md
            - ScikitLearn: modelserving/v1beta1/sklearn/v2/README.md
            - XGBoost: modelserving/v1beta1/xgboost/README.md
            - PMML: modelserving/v1beta1/pmml/README.md
            - How to write a custom predictor: modelserving/v1beta1/custom/custom_model/README.md
          - Multi Model Serving:
                - Triton: modelserving/mms/triton.md
                - MLServer: modelserving/mms/mlserver.md
          - Transformers:
                - Feast: modelserving/v1beta1/transformer/feast/README.md
                - How to write a custom transformer: modelserving/v1beta1/transformer/torchserve_image_transformer/README.md
          - Explainers:
                - Alibi Explainer: modelserving/explainer/alibi/alibi.md
                - AIX Explainer: modelserving/explainer/aix/mnist/aix.md
          - Drift/Outlier Detection:
                - Alibi Detect: modelserving/detect/alibi_detect.md
    - API Reference:
          - Control Plane API: reference/api.md
          - Python Client SDK: reference/client.md
    - Developer Guide:
          - How to contribute: developer/developer.md
          - Debugging guide: developer/debug.md
    - Community:
        - Adopters: community/adopters.md
        - Roadmap: community/roadmap.md
        - Demos and Presentations: community/presentations.md

site_name: KServe 
site_url: https://kserve.io/docs
site_description: KServe Documentation
extra_css:
  - stylesheets/extra.css

repo_url: https://github.com/kserve/website
edit_uri: edit/mkdocs/docs

theme:
  name: material
  logo: images/logo/kserve.png
  features:
    - navigation.tabs
    - navigation.tracking
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top

markdown_extensions:
  # - mdx_include:
  #     base_path: docs
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - meta
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.snippets:
      base_path: docs/snippets
  - pymdownx.keys
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.escapeall
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - toc:
      permalink: true
  - def_list

copyright: "Copyright Â© 2021 The KServe Authors"

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kserve/community
      name: KServe Community on Github
    - icon: fontawesome/brands/slack
      link: https://kubeflow.slack.com/join/shared_invite/zt-n73pfj05-l206djXlXk5qdQKs4o1Zkg#
      name: Slack
  # TODO: Replace with https://github.com/mkdocs/mkdocs/pull/2267 once mkdocs 1.2 is out.
  version_warning: !!python/object/apply:os.getenv ["VERSION_WARNING"]
  kserve_version: !!python/object/apply:os.getenv ["KSERVE_VERSION"]
  branch: !!python/object/apply:os.getenv ["SAMPLES_BRANCH", "mkdocs"]
