[build]
publish = "build"
command = "npm run update-preview-config && npm run build --dev"
environment = { NODE_VERSION = "20", NPM_VERSION = "9", NPM_FLAGS = "--no-audit --no-fund", NODE_ENV = "development" }
